### ISSUE TITLE
프로젝트 초기 설정

### ISSUE THREAD

**Issue by pnr98** [pnr98/portfolio-walkeu#1]
### Task
- [ ] 와이어프레임 작성
- [ ] 목업 작성 
- [ ] 유저플로우 작성
- [ ] 요구사항명세서 작성 
- [ ] 깃헙 이슈 추가
- [ ] 브랜치 전략 설정
- [ ] 커밋 컨벤션 설정

### Tool
* figma, miro, notion
