### ISSUE TITLE
개발환경 세팅

### ISSUE THREAD

**Issue by pnr98** [pnr98/portfolio-walkeu#2]
### Task
- [x] React 설치 및 설정
* React 프로젝트 초기화
* 필요한 패키지 설치 (e.g., react-router-dom)

- [ ] 폴더 구조 설정
* src, components, pages, assets 등 폴더 생성
* 폴더 구조 문서화

- [ ] ESLint 및 Prettier 설정
* ESLint 설치 및 설정 파일 작성
* Prettier 설치 및 설정 파일 작성
* 코드 스타일 규칙 정의

- [x] Styled-Components 설정
* styled-components 설치
* 테마 및 글로벌 스타일 설정

- [ ] Redux 설정
* Redux 및 관련 패키지 설치 (e.g., redux-toolkit, react-redux)
* 스토어 설정 및 기본 리듀서 작성

- [ ] Axios 설정
* Axios 설치
* 기본 API 설정 파일 작성

- [ ] Express 설정
* Express 설치 및 기본 서버 설정
* 필요한 미들웨어 추가 (e.g., body-parser, cors)

### 참고사항
* ㅇㅇ
* https://prettier.io/docs/en/options.html
